steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'northamerica-northeast1-docker.pkg.dev/nirmal-ml/myrepo/testimage:${SHORT_SHA}',
            '-t',
            'northamerica-northeast1-docker.pkg.dev/nirmal-ml/myrepo/testimage:latest',
            '--cache-from',
            'northamerica-northeast1-docker.pkg.dev/nirmal-ml/myrepo/testimage:latest',
            '--file',
            'Dockerfile',  # Assuming Dockerfile is in the same directory
            '.'
          ]
